version: '2'

services:
 mongodb:
        container_name: "mongodb"
        image: mongo:latest
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/mongodb
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
 
 redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis
    restart: always

  
 mysql:
    container_name: "mysql"
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data/mysql


 rabbitmq:
  container_name: "rabbitmq"
  image: "rabbitmq:3-management"
  hostname: "rabbitmq"
  environment:
    RABBITMQ_DEFAULT_USER: "root"
    RABBITMQ_DEFAULT_PASS: "password"
    RABBITMQ_DEFAULT_VHOST: "/"
  ports:
    - "15672:15672"
    - "5672:5672"
  volumes:
    - "./data/rabbitmq"
    #- "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
    #- "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"

 

 elasticsearch:
    image: elasticsearch:6.5.0
    ports:
      - "9200:9200"
    volumes:
      - ./data/elasticsearch/

 kibana:
    image: kibana:6.5.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
